CPW219-eCommerceSite/Controllers/GamesController.cs
using CPW219_eCommerceSite.Data;
using CPW219_eCommerceSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CPW219_eCommerceSite.Controllers
{  
    public class GamesController : Controller
    {
        // added this with constructor by right clicking it added parameters and set to it
        // readonly makes it so we cannot reassign to else where in class
        private readonly VideoGameContext _context;

        public GamesController(VideoGameContext context)
        {
            _context = context;
        }
        
        public async Task<IActionResult> Index(int? id) // int id has to do with mapping
        {
            const int NumGamesToDisplayPerPage = 3;
            const int PageOffSet = 1; // Need a page offset to use current page and figure out, nums game to skip
            

            // Set currPage to id if it has a value, otherwise use 1
            int currPage = id ?? 1; // sort cut way of writing of id id.hasvalue then currPage == id.value

            int totalNumOfProducts = await _context.Games.CountAsync();
            double maxNumPages = Math.Ceiling((double)totalNumOfProducts / NumGamesToDisplayPerPage);
            int lastPage = Convert.ToInt32(maxNumPages); // Rounding pages up to next whole number

            // query syntax
            List<Game> games = await (from game in _context.Games
                                      select game)
                                      .Skip(NumGamesToDisplayPerPage * (currPage - PageOffSet))
                                      .Take(NumGamesToDisplayPerPage)
                                      .ToListAsync();

            GameCatelogViewModel catalogModel = new(games, lastPage, currPage);


            // Show them on the page
            return View(catalogModel);

        }

        [HttpGet]
        // To add razor view right click on create then will show up
        public IActionResult Create()
        {
            
            return View();
        }


        [HttpPost]
        //await and async added keywords make more efficient for traffic
        // https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/using-asynchronous-methods-in-aspnet-mvc-4
        public async Task<IActionResult> Create(Game game)
        {
            if (ModelState.IsValid)
            {
                // Add game to DB
                _context.Games.Add(game); // Prepares insert
                await _context.SaveChangesAsync(); // Executes pending insert

                // Show success message on page
                ViewData["Message"] = $"{game.Title} was added successfully";
                //TempData - keeps data when redirected to a new page

                return View();
            }
            return View(game);
        }

        //async needs task 
        public async Task<IActionResult> Edit(int id)
        {
            Game? gameToEdit = await _context.Games.FindAsync(id);

            if (gameToEdit == null)
            {
                return NotFound();
            }

            return View(gameToEdit);
        }

        // Model binding 
        [HttpPost]
        public async Task<IActionResult> Edit(Game gameModel)
        {
            if (ModelState.IsValid)
            {
                _context.Games.Update(gameModel);
                await _context.SaveChangesAsync();

                TempData["Message"] = $"{gameModel.Title} was updated successfully";
                return RedirectToAction("Index");
            }
            return View(gameModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            // find game by id
            Game? gameToDelete = await _context.Games.FindAsync(id);

            if (gameToDelete == null)
            {
                return NotFound();
            }
            return View(gameToDelete);
        }

        // so when post it's like posting to a method called post so c# doestn yell at us
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Game gameToDelete = await _context.Games.FindAsync(id);

            if (gameToDelete != null)
            {
                _context.Games.Remove(gameToDelete);
                await _context.SaveChangesAsync();
                TempData["Message"] = gameToDelete.Title + " was deleted successfully";
                return RedirectToAction("index");
            }
            TempData["Message"] = "This game was already deleted";
            return RedirectToAction("Index");
            
        }

        public async Task<IActionResult> Details(int id)
        {
            Game? gameDetails = await _context.Games.FindAsync(id);

            if (gameDetails == null)
            {
                return NotFound();
            }

            return View(gameDetails);

        }
    }
}

CPW219-eCommerceSite/Controllers/MembersController.cs
using CPW219_eCommerceSite.Data;
using CPW219_eCommerceSite.Models;
using Microsoft.AspNetCore.Mvc;

namespace CPW219_eCommerceSite.Controllers
{
    public class MembersController : Controller
    {
        private readonly VideoGameContext _context;

        // controller do ctor tab tab
        // database context to access anywhere in this controller
        public MembersController(VideoGameContext context)
        {
            _context = context;
        }
        // added this in controllers and is a Mvc empty
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost] //when send info and make sure you are using the proper model
        public async Task<IActionResult> Register(RegisterViewModel regmModel)
        {
            if (ModelState.IsValid)
            {
                // Map registerViewModel data to member object
                Member newMember = new()
                {
                    Email = regmModel.Email,
                    Password = regmModel.Password

                };

                _context.Members.Add(newMember);
               await  _context.SaveChangesAsync();

                // when register it logs in user
                LogUserIn(newMember.Email);

                // REdirect to home page
                //index of the home controller
                return RedirectToAction("Index", "Home");

            }
            return View(regmModel);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        // be careful when searching for information
        // asp.net state meanagement is important to knowa
        // 
        [HttpPost]
        public IActionResult Login(LoginViewModel loginModel)
        {
            if (ModelState.IsValid)
            {
                // Check DB for credentials
                // member? because the member might not be in there
                Member? mLogin = (from member in _context.Members
                                where member.Email == loginModel.Email &&
                                    member.Password == loginModel.Password
                                select member).SingleOrDefault();

                // If exists, send to homepage
                if (mLogin != null)
                {
                    // sets the session
                    LogUserIn(loginModel.Email);
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError(string.Empty, "Credentials not found");

            }
            // Return page if no record found, or ModelState is invalid
            return View(loginModel);
        }

        private void LogUserIn(string email)
        {
            HttpContext.Session.SetString("Email", email);
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

CPW219-eCommerceSite/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor _httpContext

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jade's Gaming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CPW219_eCommerceSite.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jade's Gaming</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                         @*controller- set to games and action and want to go to index of game controller*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Game Catalog</a>
                        </li>

                        @{
                            string? userEmail = _httpContext.HttpContext.Session.GetString("Email");
                        }

                        @if(userEmail == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Login">Log in</a>
                            </li>
                        }

                        else
                        {
                            <li>
                                <p>Hello @userEmail</p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Logout">Log Out</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Jade's Gaming' - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>